- name: jackett | copy ServerConfig.json
  copy:
    src: jackett/ServerConfig.json
    dest: /data/config/jackett/Jackett/ServerConfig.json
    backup: yes
    mode: 0640
    owner: media
    group: media

- name: jackett | copy indexers json files
  copy:
    src: jackett/Indexers
    dest: /data/config/jackett/Jackett/
    backup: yes
    mode: 0640
    owner: media
    group: media
  failed_when: false
  ignore_errors: true
